### ISSUE TITLE
Format Namespace according to psr-2

### ISSUE THREAD

**Issue by ctf0** [phpfmt/sublime-phpfmt#216] opened 2015-11-29 12:08 UTC
hello again, many thanx for the latest updates, here is what am having atm

1- the namespace doesnt get formated acoording to psr-2 like
```php
<?php namespace app/x/y
```
after you run the formatting it should be 
```php
<?php 

namespace app/x/y
```
 but it doesnt get updated.

**Comment by ccirello** [comment] 2015-11-29 14:40
Thanks for the appreciation @ctf0 

Please, close this issue and open two distinct ones. Wrt item 1, I think it is a bug.
Wrt item 2, I didn't understand what you meant. Could you please elaborate in the other issue you should be about to create?

**Comment by ctf0** [comment] 2015-11-29 15:29
done, i will make another issue for that.

**Comment by ccirello** [comment] 2015-11-29 18:13
Working as intended. (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#3-namespace-and-use-declarations). It says:

```
3. Namespace and Use Declarations

When present, there MUST be one blank line after the namespace declaration.

When present, all use declarations MUST go after the namespace declaration.

There MUST be one use keyword per declaration.

There MUST be one blank line after the use block.
```

As you can see, there is not mention whatsoever about add a linebreak _before_ namespace declaration.

In PSR-1 (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#21-php-tags), it mentions the use of `<?php` but does not declare anything about line breaks.

**Closed by ccirello** 2015-11-29 18:13 UTC
Labels: question, wontfix

**Comment by ctf0** [comment] 2015-11-29 18:20
here is for the psr2 https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md
